@url= http://localhost:3000

GET {{url}}/hello/
###

GET {{url}}/employees/
###

GET {{url}}/reports/salaries
###

GET {{url}}/employees/98be64d0e0d8c96e08ec
###

POST {{url}}/employees/
Content-Type: application/json

{
    "name": "Johnathan",
    "position": "Manager",
    "salary":50000
}